from typing import Literal, Optional

from pydantic import BaseModel, Field, AliasChoices


Category = Literal[
    "TEMPLATE",
    "COMPLIANCE",
    "FILL_AND_SUBMIT",
    "REFERENCE",
    "BUDGET",
    "LEGAL",
    "FINAL_PACKAGE",
    "OTHER",
]


class Document(BaseModel):
    """
    Canonical shared schema for uploaded/source documents.

    Notes on compatibility:
    - Older code may refer to `actual_file_name` and `description`.
    - We support those as input aliases for `file_name` and `purpose`.
    """

    id: str = Field(
        default="",
        description=(
            "Do not generate this field. It is auto-generated by the system. "
            "Unique identifier for the document used to match it to the uploaded file."
        ),
    )

    file_name: str = Field(
        default="",
        validation_alias=AliasChoices("file_name", "actual_file_name", "filename"),
        description=(
            "Do not generate this field. It is auto-generated by the system. "
            "The filename of the uploaded document as provided by the user."
        ),
    )

    file_data: str = Field(
        default="",
        description=(
            "Do not generate this field. It is auto-generated by the system. "
            "The raw uploaded file payload (e.g., data:...base64,...) used by the system."
        ),
    )

    document_type: Optional[str] = Field(
        default=None,
        description=(
            "Short, slug-friendly type of the document for identification and IDs (e.g. 'rfp', 'tor', "
            "'guidelines', 'budget_template', 'cover_letter'). "
            "Infer from filename and content (e.g. 'RFP.pdf' → 'rfp', tender requirements → 'tor')."
        ),
    )

    purpose: str = Field(
        validation_alias=AliasChoices("purpose", "description"),
        description=(
            "A clear, detailed statement of why this document exists and how it should be used. "
            "Describe the document’s role in the grant/tender workflow (e.g., instructions to comply with, "
            "template to follow, form to fill, contract terms to accept), who the intended audience is, "
            "what decisions/actions it should drive, and what outcomes it is meant to enable. "
            "Be specific about scope (what it covers and what it does not), and reference any notable "
            "requirements implied by the document (e.g., mandatory sections, deliverables, evaluation focus, "
            "submission process) without inventing facts beyond the document."
        ),
    )

    primary_category: Category = Field(
        description=(
            "The single best main category for organizing this document in the system. "
            "Choose the category that most closely represents the document's primary intent "
            "(e.g., COMPLIANCE for instructions/rules, TEMPLATE for reusable structures, "
            "FILL_AND_SUBMIT for forms/proformas to complete, BUDGET for financial templates, "
            "LEGAL for contractual terms)."
        )
    )

    categories: list[Category] = Field(
        default_factory=list,
        description=(
            "All applicable categories for this document (multi-label). "
            "Use this to capture secondary uses (e.g., a pricing schedule can be LEGAL + BUDGET, "
            "or a proposal template with embedded rules can be TEMPLATE + COMPLIANCE). "
            "The primary_category MUST also be included in this list."
        ),
    )

    how_to_use: str = Field(
        description=(
            "Instructions for how this document should be used by the agent. "
            "Specify the exact workflow actions to take with it (e.g., read first for rules, follow as a template, "
            "fill specific sections/fields, extract required attachments, derive deliverables/timeline, capture "
            "evaluation criteria and scoring). "
            "Include what to extract (deadlines, page limits, eligibility, formatting, required sections, signatures), "
            "what decisions it informs (structure, scope, deliverables, compliance gates), and how it impacts downstream "
            "tasks (writing, budgeting, validation, submission packaging)."
        )
    )

    key_facts: list[str] = Field(
        default_factory=list,
        description=(
            "Verified, reusable facts extracted directly from this document. "
            "Each item should be a single, atomic statement (one fact per bullet) that can be used later in writing, "
            "form-filling, budgeting, compliance checks, or planning. "
            "Prefer concrete, decision-useful facts such as: deadlines and time windows, submission method/portal, "
            "eligibility constraints, geographic/sector scope, required sections and headings, deliverables and outputs, "
            "reporting cadence, evaluation criteria and weighting (if stated), page/word limits, formatting requirements, "
            "required attachments, contact points, and key definitions. "
            "Do not invent numbers, dates, names, or requirements—only include what the document states."
        ),
    )

    critical_compliance_rules: list[str] = Field(
        default_factory=list,
        description=(
            "Non-negotiable rules that MUST be satisfied to avoid disqualification/rejection. "
            "Write each rule as a testable requirement (e.g., 'Submission must be received by [DEADLINE]', "
            "'Proposal must not exceed [PAGE_LIMIT] pages', 'Include signed [DECLARATION_NAME] form'). "
            "Capture anything that would fail compliance if missed: deadlines, mandatory forms/annexes, signature/stamp "
            "requirements, file formats and naming, submission channels, eligibility gates, required policies "
            "(e.g., safeguarding), minimum/maximum limits, and any stated 'mandatory' conditions. "
            "If the document specifies consequences (e.g., 'will be rejected'), include that wording. "
            "Do not add rules not explicitly present in the document."
        ),
    )

