import json
from langchain.tools import tool, ToolRuntime
from langchain_core.messages import ToolMessage
from langgraph.types import Command

from .description import TOOL_DESCRIPTION
from .schema import ColocationInput


@tool("quantify_colocation_benefits", description=TOOL_DESCRIPTION)
def quantify_colocation_benefits_tool(
    payload: ColocationInput, runtime: ToolRuntime
) -> Command:
    """Calculates CAPEX savings ($120-180M) generated by co-locating infrastructure."""

    # In a real-world scenario, this tool would:
    # 1. Compare 'Greenfield' costs vs 'Co-location' costs for civil works.
    # 2. Calculate the overlap percentage between the transmission line and the highway.
    # 3. Estimate savings from shared Environmental Impact Assessments (EIAs).

    response = {
        "colocation_savings_usd": 155000000,
        "overlap_percentage": "82%",
        "savings_breakdown": {
            "civil_works_and_access": "$85M",
            "land_acquisition": "$40M",
            "logistics_and_security": "$30M",
        },
        "message": "Co-location benefits quantified; significant savings in civil works detected.",
    }

    return Command(
        update={
            "messages": [
                ToolMessage(
                    content=json.dumps(response), tool_call_id=runtime.tool_call_id
                )
            ]
        }
    )
