import json
from langchain.tools import tool, ToolRuntime
from langchain_core.messages import ToolMessage
from langgraph.types import Command

from .description import TOOL_DESCRIPTION


@tool("quantify_colocation_benefits", description=TOOL_DESCRIPTION)
def quantify_colocation_benefits_tool(runtime: ToolRuntime) -> Command:
    """Calculates CAPEX savings generated by co-locating transmission infrastructure with highway corridor."""

    # In a real-world scenario, this tool would:
    # 1. Compare 'Greenfield' costs vs 'Co-location' costs for civil works.
    # 2. Calculate the overlap percentage between the transmission line and the highway.
    # 3. Estimate savings from shared Environmental Impact Assessments (EIAs).

    response = {
        "status": "Co-location Analysis Complete",
        "job_metadata": {
            "tool": "quantify_colocation_benefits",
            "corridor_id": "ABIDJAN_LAGOS_CORRIDOR",
            "variants_analysed": 5,
            "shared_infrastructure_types_assessed": [
                "access_roads",
                "land_clearing",
                "land_acquisition",
                "security",
                "eia_and_permitting",
                "construction_logistics",
            ],
            "baseline": "Greenfield standalone transmission line — no highway co-location",
            "generated_at": "2026-01-26T10:45:00+00:00",
        },
        # ── SAVINGS METHODOLOGY ────────────────────────────────────────────────
        "savings_methodology": {
            "description": "Savings calculated by comparing full greenfield unit costs against co-located unit costs, applied proportionally to the refined highway overlap percentage per variant.",
            "greenfield_unit_costs": {
                "access_roads_per_km": 180000,
                "land_clearing_per_km": 95000,
                "land_acquisition_per_km": 210000,
                "security_per_km_per_year": 12000,
                "eia_standalone_cost": 8500000,
                "construction_logistics_per_km": 145000,
            },
            "co_location_unit_costs": {
                "access_roads_per_km": 22000,
                "land_clearing_per_km": 18000,
                "land_acquisition_per_km": 38000,
                "security_per_km_per_year": 4500,
                "eia_shared_cost": 2800000,
                "construction_logistics_per_km": 61000,
            },
            "savings_rate_per_category": {
                "access_roads": "88% saving — highway construction roads used directly",
                "land_clearing": "81% saving — corridor already cleared for highway works",
                "land_acquisition": "82% saving — within existing RoW, no new acquisition",
                "security": "63% saving — shared perimeter and patrol roads",
                "eia_and_permitting": "67% saving — joint ESIA filed under corridor master plan",
                "construction_logistics": "58% saving — shared equipment mobilisation and camps",
            },
        },
        # ── PER VARIANT ANALYSIS ───────────────────────────────────────────────
        "variant_colocation_analysis": [
            {
                "variant_id": "ROUTE-V1",
                "label": "Recommended — Coastal Highway Co-location",
                "refined_length_km": 1082.5,
                "refined_highway_overlap_pct": 71,
                "co_located_length_km": 768.6,
                "standalone_length_km": 313.9,
                # ── GREENFIELD BASELINE ────────────────────────────────────────
                "greenfield_baseline": {
                    "description": "What this route would cost if built as a completely standalone transmission line with no highway co-location",
                    "access_roads_usd": 194850000,
                    "land_clearing_usd": 102837500,
                    "land_acquisition_usd": 227325000,
                    "security_usd": 12990000,
                    "eia_and_permitting_usd": 8500000,
                    "construction_logistics_usd": 156962500,
                    "total_greenfield_civil_usd": 703465000,
                },
                # ── CO-LOCATION ACTUAL COST ────────────────────────────────────
                "colocation_actual_cost": {
                    "description": "Actual civil costs after applying co-location savings to the 71% overlapping section",
                    "access_roads_usd": 45716400,
                    "land_clearing_usd": 27520800,
                    "land_acquisition_usd": 66505800,
                    "security_usd": 8073900,
                    "eia_and_permitting_usd": 2800000,
                    "construction_logistics_usd": 82110000,
                    "total_colocation_civil_usd": 232726900,
                },
                # ── SAVINGS ────────────────────────────────────────────────────
                "total_colocation_savings_usd": 182180000,
                "savings_as_pct_of_gross_capex": 13.5,
                "savings_breakdown": {
                    "access_roads": {
                        "saving_usd": 85420000,
                        "saving_pct": 43.8,
                        "notes": "Highway construction roads available for 768.6km. Only 313.9km requires new access track cutting.",
                    },
                    "land_clearing": {
                        "saving_usd": 38200000,
                        "saving_pct": 19.6,
                        "notes": "Corridor already cleared for highway works across 71% of route. Dense bush clearing only needed for standalone sections.",
                    },
                    "land_acquisition": {
                        "saving_usd": 31820000,
                        "saving_pct": 16.3,
                        "notes": "No new land purchase within existing RoW (768.6km). Strip acquisition only for 313.9km standalone sections at avg $12,000/ha.",
                    },
                    "security": {
                        "saving_usd": 8740000,
                        "saving_pct": 4.5,
                        "notes": "Shared security perimeter and patrol roads for co-located sections. Covers 10-year construction and early operations period.",
                    },
                    "eia_and_permitting": {
                        "saving_usd": 5700000,
                        "saving_pct": 2.9,
                        "notes": "Joint ESIA filed under ALCOMA corridor master plan. Shared environmental baseline studies, community consultations, and regulatory submissions.",
                    },
                    "construction_logistics": {
                        "saving_usd": 12300000,
                        "saving_pct": 6.3,
                        "notes": "Shared equipment mobilisation, worker camps, and fuel depots with highway construction teams for co-located sections.",
                    },
                },
                # ── SEGMENT LEVEL BREAKDOWN ────────────────────────────────────
                "segment_savings": [
                    {
                        "segment_id": "V1-SEG-001-R",
                        "label": "Abidjan → Tema",
                        "length_km": 318.4,
                        "highway_overlap_pct": 78,
                        "co_located_length_km": 248.4,
                        "colocation_savings_usd": 70550000,
                        "savings_pct_of_segment_capex": 17.0,
                        "primary_saving_driver": "Access roads — N1 highway construction corridor fully operational, crews already mobilised.",
                    },
                    {
                        "segment_id": "V1-SEG-002-R",
                        "label": "Tema → Lomé",
                        "length_km": 191.2,
                        "highway_overlap_pct": 44,
                        "co_located_length_km": 84.1,
                        "colocation_savings_usd": 19710000,
                        "savings_pct_of_segment_capex": 8.7,
                        "primary_saving_driver": "Limited co-location due to Volta delta re-route — savings concentrated in Accra-Tema section only.",
                        "notes": "Lowest co-location savings of all segments. Volta delta pile foundation section is standalone — no highway overlap possible across wetland.",
                    },
                    {
                        "segment_id": "V1-SEG-003-R",
                        "label": "Lomé → Cotonou",
                        "length_km": 154.6,
                        "highway_overlap_pct": 83,
                        "co_located_length_km": 128.3,
                        "colocation_savings_usd": 27840000,
                        "savings_pct_of_segment_capex": 16.0,
                        "primary_saving_driver": "High highway overlap — flat coastal terrain, well-established N1 corridor with active construction access.",
                    },
                    {
                        "segment_id": "V1-SEG-004-R",
                        "label": "Cotonou → Lagos",
                        "length_km": 418.3,
                        "highway_overlap_pct": 64,
                        "co_located_length_km": 267.7,
                        "colocation_savings_usd": 64080000,
                        "savings_pct_of_segment_capex": 12.0,
                        "primary_saving_driver": "Land acquisition savings dominant — Lagos corridor land values extremely high ($85,000/ha), RoW sharing critical.",
                        "notes": "Underground Lagos section has no co-location saving on cable installation but shares duct routing with highway drainage infrastructure.",
                    },
                ],
                "recommendation": "HIGHEST CO-LOCATION VALUE — Best balance of overlap percentage and route length. Proceed as recommended variant.",
            },
            {
                "variant_id": "ROUTE-V2",
                "label": "Inland Detour — Maximum Terrain Avoidance",
                "refined_length_km": 1138.9,
                "refined_highway_overlap_pct": 54,
                "co_located_length_km": 615.0,
                "standalone_length_km": 523.9,
                "greenfield_baseline": {
                    "access_roads_usd": 204902000,
                    "land_clearing_usd": 108195500,
                    "land_acquisition_usd": 239169000,
                    "security_usd": 13666800,
                    "eia_and_permitting_usd": 8500000,
                    "construction_logistics_usd": 165140500,
                    "total_greenfield_civil_usd": 739573800,
                },
                "colocation_actual_cost": {
                    "access_roads_usd": 68234000,
                    "land_clearing_usd": 41820000,
                    "land_acquisition_usd": 108420000,
                    "security_usd": 9880000,
                    "eia_and_permitting_usd": 3200000,
                    "construction_logistics_usd": 108399000,
                    "total_colocation_civil_usd": 339953000,
                },
                "total_colocation_savings_usd": 109620000,
                "savings_as_pct_of_gross_capex": 9.0,
                "savings_breakdown": {
                    "access_roads": {
                        "saving_usd": 48200000,
                        "saving_pct": 44.0,
                        "notes": "Only 54% highway overlap — 523.9km requires new access track cutting through inland agricultural and forest areas.",
                    },
                    "land_clearing": {
                        "saving_usd": 24800000,
                        "saving_pct": 22.6,
                        "notes": "Inland sections require significant new clearing. Some areas require dry-season-only access due to seasonal flooding.",
                    },
                    "land_acquisition": {
                        "saving_usd": 19600000,
                        "saving_pct": 17.9,
                        "notes": "Higher per-hectare acquisition cost inland ($18,000/ha avg) partially offset by lower total area needed vs coastal route.",
                    },
                    "security": {
                        "saving_usd": 5820000,
                        "saving_pct": 5.3,
                        "notes": "Inland sections require dedicated security — less highway traffic for natural surveillance.",
                    },
                    "eia_and_permitting": {
                        "saving_usd": 5300000,
                        "saving_pct": 4.8,
                        "notes": "Partial ESIA sharing — inland sections require separate environmental baseline studies for different ecosystems.",
                    },
                    "construction_logistics": {
                        "saving_usd": 5900000,
                        "saving_pct": 5.4,
                        "notes": "Limited logistics sharing — inland route has fewer established supply chain nodes.",
                    },
                },
                "notes": "Co-location savings $72.6M less than ROUTE-V1 despite being longer — lower overlap percentage is the primary driver. The inland detour that avoids terrain complexity also avoids the highway, eliminating co-location opportunity.",
                "recommendation": "LOWER CO-LOCATION VALUE — Terrain avoidance benefits do not compensate for lost co-location savings vs ROUTE-V1.",
            },
            {
                "variant_id": "ROUTE-V3",
                "label": "Shortest Path — Minimum Distance",
                "refined_length_km": 1071.4,
                "refined_highway_overlap_pct": 38,
                "co_located_length_km": 407.1,
                "standalone_length_km": 664.3,
                "greenfield_baseline": {
                    "access_roads_usd": 192852000,
                    "land_clearing_usd": 101783000,
                    "land_acquisition_usd": 224994000,
                    "security_usd": 12856800,
                    "eia_and_permitting_usd": 8500000,
                    "construction_logistics_usd": 155353000,
                    "total_greenfield_civil_usd": 696338800,
                },
                "colocation_actual_cost": {
                    "access_roads_usd": 100820000,
                    "land_clearing_usd": 62440000,
                    "land_acquisition_usd": 151260000,
                    "security_usd": 10180000,
                    "eia_and_permitting_usd": 4800000,
                    "construction_logistics_usd": 110738000,
                    "total_colocation_civil_usd": 440238000,
                },
                "total_colocation_savings_usd": 56080000,
                "savings_as_pct_of_gross_capex": 4.0,
                "savings_breakdown": {
                    "access_roads": {
                        "saving_usd": 22400000,
                        "saving_pct": 39.9,
                        "notes": "Only 38% highway overlap — majority of route cuts directly through countryside with no existing access infrastructure.",
                    },
                    "land_clearing": {
                        "saving_usd": 14200000,
                        "saving_pct": 25.3,
                        "notes": "Direct path crosses more undisturbed land — clearing costs high for 664.3km standalone sections.",
                    },
                    "land_acquisition": {
                        "saving_usd": 10800000,
                        "saving_pct": 19.2,
                        "notes": "Lowest land acquisition saving of all variants — route crosses multiple private landholdings not within any existing corridor.",
                    },
                    "security": {
                        "saving_usd": 3800000,
                        "saving_pct": 6.8,
                        "notes": "Dedicated security required for most of route — isolated from highway surveillance.",
                    },
                    "eia_and_permitting": {
                        "saving_usd": 3700000,
                        "saving_pct": 6.6,
                        "notes": "Separate ESIA processes required for sections outside corridor master plan boundary.",
                    },
                    "construction_logistics": {
                        "saving_usd": 1180000,
                        "saving_pct": 2.1,
                        "notes": "Minimal logistics sharing — standalone route requires full independent mobilisation for most sections.",
                    },
                },
                "critical_finding": "ROUTE-V3 appeared cheapest at strategic level but is actually most expensive on net CAPEX basis. Shortest distance + lowest co-location savings = highest net cost. Net CAPEX $179M more than ROUTE-V1 despite being 11.1km shorter in refined length.",
                "recommendation": "POOREST CO-LOCATION VALUE — Avoid. Short distance advantage completely eliminated by low overlap and high standalone civil costs.",
            },
            {
                "variant_id": "ROUTE-V4",
                "label": "Maximum Anchor Load Coverage",
                "refined_length_km": 1159.7,
                "refined_highway_overlap_pct": 65,
                "co_located_length_km": 753.8,
                "standalone_length_km": 405.9,
                "greenfield_baseline": {
                    "access_roads_usd": 208746000,
                    "land_clearing_usd": 110171500,
                    "land_acquisition_usd": 243537000,
                    "security_usd": 13916400,
                    "eia_and_permitting_usd": 8500000,
                    "construction_logistics_usd": 168140500,
                    "total_greenfield_civil_usd": 753011400,
                },
                "colocation_actual_cost": {
                    "access_roads_usd": 57820000,
                    "land_clearing_usd": 34200000,
                    "land_acquisition_usd": 82440000,
                    "security_usd": 9340000,
                    "eia_and_permitting_usd": 2800000,
                    "construction_logistics_usd": 93101400,
                    "total_colocation_civil_usd": 279701400,
                },
                "total_colocation_savings_usd": 193310000,
                "savings_as_pct_of_gross_capex": 13.0,
                "savings_breakdown": {
                    "access_roads": {
                        "saving_usd": 88200000,
                        "saving_pct": 45.6,
                        "notes": "Strong highway overlap for main trunk. Obuasi and Akosombo spurs use mining company access roads — comparable saving to highway co-location.",
                    },
                    "land_clearing": {
                        "saving_usd": 38900000,
                        "saving_pct": 20.1,
                        "notes": "Mining company land already cleared around Obuasi operations — additional saving beyond highway co-location.",
                    },
                    "land_acquisition": {
                        "saving_usd": 38800000,
                        "saving_pct": 20.1,
                        "notes": "AngloGold Ashanti has existing land rights along Obuasi spur route — easement agreement likely vs new acquisition.",
                    },
                    "security": {
                        "saving_usd": 9600000,
                        "saving_pct": 5.0,
                        "notes": "Mining company security infrastructure shared along Obuasi spur — high-quality perimeter already established.",
                    },
                    "eia_and_permitting": {
                        "saving_usd": 5700000,
                        "saving_pct": 2.9,
                        "notes": "Obuasi mine has existing environmental permits and baseline data — reduces ESIA scope significantly.",
                    },
                    "construction_logistics": {
                        "saving_usd": 12110000,
                        "saving_pct": 6.3,
                        "notes": "Mining supply chain and worker accommodation available for Obuasi spur construction.",
                    },
                },
                "notes": "ROUTE-V4 achieves highest absolute colocation savings ($193.3M) — slightly above ROUTE-V1 ($182.2M) due to mining infrastructure co-location on Obuasi spur partially substituting for highway co-location. However gross CAPEX is also $138M higher, so net CAPEX remains $127M above ROUTE-V1.",
                "recommendation": "HIGHEST ABSOLUTE CO-LOCATION SAVINGS but does not overcome higher gross CAPEX. Justified only if anchor load revenue projections ($116M/year Year 5) are high-confidence.",
            },
            {
                "variant_id": "ROUTE-V5",
                "label": "Minimum Environmental Footprint",
                "refined_length_km": 1201.3,
                "refined_highway_overlap_pct": 59,
                "co_located_length_km": 708.8,
                "standalone_length_km": 492.5,
                "greenfield_baseline": {
                    "access_roads_usd": 216234000,
                    "land_clearing_usd": 114123500,
                    "land_acquisition_usd": 252273000,
                    "security_usd": 14415600,
                    "eia_and_permitting_usd": 8500000,
                    "construction_logistics_usd": 174188500,
                    "total_greenfield_civil_usd": 779734600,
                },
                "colocation_actual_cost": {
                    "access_roads_usd": 74820000,
                    "land_clearing_usd": 44320000,
                    "land_acquisition_usd": 112140000,
                    "security_usd": 9880000,
                    "eia_and_permitting_usd": 2200000,
                    "construction_logistics_usd": 118094600,
                    "total_colocation_civil_usd": 361454600,
                },
                "total_colocation_savings_usd": 138480000,
                "savings_as_pct_of_gross_capex": 12.0,
                "savings_breakdown": {
                    "access_roads": {
                        "saving_usd": 61200000,
                        "saving_pct": 44.2,
                        "notes": "Moderate savings — environmental buffers push 41% of route outside highway corridor requiring new access.",
                    },
                    "land_clearing": {
                        "saving_usd": 28600000,
                        "saving_pct": 20.7,
                        "notes": "Wide environmental berths mean more undisturbed land to clear on standalone sections.",
                    },
                    "land_acquisition": {
                        "saving_usd": 26400000,
                        "saving_pct": 19.1,
                        "notes": "Standalone sections frequently cross agricultural land — higher acquisition cost than corridor sections.",
                    },
                    "security": {
                        "saving_usd": 7600000,
                        "saving_pct": 5.5,
                        "notes": "Remote standalone sections require dedicated security patrols.",
                    },
                    "eia_and_permitting": {
                        "saving_usd": 6300000,
                        "saving_pct": 4.5,
                        "notes": "BEST ESIA SAVING — Lowest environmental complexity means shared ESIA is faster and cheaper. Estimated 14-month process vs 20-month for ROUTE-V1. Saving includes avoided specialist studies.",
                    },
                    "construction_logistics": {
                        "saving_usd": 8380000,
                        "saving_pct": 6.0,
                        "notes": "Longer route increases total logistics cost but co-located sections share highway supply chain.",
                    },
                },
                "notes": "ROUTE-V5 has moderate co-location savings despite being the longest route. Environmental buffers that define this variant also reduce highway overlap, capping co-location benefit.",
                "recommendation": "MODERATE CO-LOCATION VALUE — Best ESIA saving of all variants. Suitable if permitting speed is prioritised over maximum co-location savings.",
            },
        ],
        # ── COMPARATIVE SUMMARY ────────────────────────────────────────────────
        "comparative_summary": {
            "variant_ranking_by_colocation_savings": [
                {
                    "rank": 1,
                    "variant_id": "ROUTE-V4",
                    "total_savings_usd": 193310000,
                    "savings_pct": 13.0,
                    "overlap_pct": 65,
                    "net_capex_usd": 1293690000,
                },
                {
                    "rank": 2,
                    "variant_id": "ROUTE-V1",
                    "total_savings_usd": 182180000,
                    "savings_pct": 13.5,
                    "overlap_pct": 71,
                    "net_capex_usd": 1166820000,
                },
                {
                    "rank": 3,
                    "variant_id": "ROUTE-V5",
                    "total_savings_usd": 138480000,
                    "savings_pct": 12.0,
                    "overlap_pct": 59,
                    "net_capex_usd": 1015520000,
                },
                {
                    "rank": 4,
                    "variant_id": "ROUTE-V2",
                    "total_savings_usd": 109620000,
                    "savings_pct": 9.0,
                    "overlap_pct": 54,
                    "net_capex_usd": 1108380000,
                },
                {
                    "rank": 5,
                    "variant_id": "ROUTE-V3",
                    "total_savings_usd": 56080000,
                    "savings_pct": 4.0,
                    "overlap_pct": 38,
                    "net_capex_usd": 1345920000,
                },
            ],
            "key_insights": [
                "ROUTE-V1 delivers best savings efficiency — 13.5% savings rate on gross CAPEX, highest of all variants. Higher overlap percentage (71%) on a shorter route outperforms ROUTE-V4's higher absolute saving.",
                "ROUTE-V3 is definitively eliminated — shortest distance but lowest co-location savings produces highest net CAPEX of all variants at $1.346B. 38% overlap is insufficient to make shortest-path economics work.",
                "ROUTE-V4 saves most in absolute terms ($193.3M) but still costs $127M more net than ROUTE-V1 — anchor load revenue must materialize to justify premium.",
                "Mining infrastructure co-location on ROUTE-V4 Obuasi spur demonstrates that co-location savings extend beyond highway corridor — any existing linear infrastructure can generate equivalent benefits.",
                "ROUTE-V5 ESIA saving ($6.3M, 14-month process vs 20-month) may be worth more than its dollar value if permitting is the project critical path — time-value of earlier revenue start could add $15-25M NPV.",
            ],
            "recommended_variant": "ROUTE-V1",
            "recommendation_rationale": "ROUTE-V1 achieves the best net CAPEX position ($1.167B) among variants with strong anchor load coverage. 71% highway overlap and 13.5% savings rate confirm co-location strategy is working optimally. Proceed to voltage sizing and substation placement on ROUTE-V1.",
        },
        "output_uris": {
            "colocation_analysis_csv": "s3://corridor-platform/data/ABIDJAN_LAGOS_CORRIDOR/colocation/colocation_savings_all_variants.csv",
            "segment_savings_breakdown": "s3://corridor-platform/data/ABIDJAN_LAGOS_CORRIDOR/colocation/segment_level_savings_V1.csv",
            "greenfield_vs_colocation_comparison": "s3://corridor-platform/data/ABIDJAN_LAGOS_CORRIDOR/colocation/greenfield_vs_colocation_matrix.csv",
        },
        "message": "Co-location benefits quantified across all 5 refined variants. ROUTE-V1 recommended — $182.2M savings (13.5% of gross CAPEX) from 71% highway overlap. ROUTE-V3 eliminated — only $56.1M savings despite shortest distance confirms that overlap percentage drives co-location value, not route length. Savings feed directly into net CAPEX figures for financing optimization.",
    }

    return Command(
        update={
            "messages": [
                ToolMessage(
                    content=json.dumps(response), tool_call_id=runtime.tool_call_id
                )
            ]
        }
    )